# Generated by Django 5.2.17 on 2026-09-10 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(blank=True, max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["acao"], name="acesso_regi_acao_1d2b0a_idx"),
                    models.Index(
                        fields=["modelo"], name="acesso_regi_modelo_2d3550_idx"
                    ),
                    models.Index(
                        fields=["criado_em"], name="acesso_regi_criado__2a8f50_idx"
                    ),
                ],
            },
        ),
    ]
