# Generated by Django 5.2.17 on 2026-09-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_relatorio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("folha", models.CharField(default="01", max_length=20)),
                ("item", models.CharField(blank=True, max_length=50, null=True)),
                ("setor", models.CharField(blank=True, max_length=150, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("motivo_solicitacao_cliente", models.BooleanField(default=False)),
                ("motivo_manutencao_corretiva", models.BooleanField(default=False)),
                ("motivo_garantia", models.BooleanField(default=False)),
                ("motivo_manutencao_preventiva", models.BooleanField(default=False)),
                ("motivo_venda", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("motivo_instalacao_irregular", models.BooleanField(default=False)),
                ("motivo_escolha_inadequada", models.BooleanField(default=False)),
                ("motivo_condicoes_criticas", models.BooleanField(default=False)),
                ("motivo_entrada_impurezas", models.BooleanField(default=False)),
                ("motivo_manuseio_irregular", models.BooleanField(default=False)),
                ("motivo_transporte_irregular", models.BooleanField(default=False)),
                ("motivo_desgaste_normal", models.BooleanField(default=False)),
                ("motivo_lacre_quebrado", models.BooleanField(default=False)),
                ("prazo_entrega", models.DateField(blank=True, null=True)),
                ("data_aprovacao", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_tecnicos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Técnico",
                "verbose_name_plural": "Relatórios Técnicos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ValvulaRelatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.PositiveIntegerField(default=1)),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                ("diametro", models.CharField(blank=True, max_length=50, null=True)),
                ("modelo", models.CharField(blank=True, max_length=150, null=True)),
                ("fabricante", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "pressao_psi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("servico", models.CharField(blank=True, max_length=150, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valvulas",
                        to="servicos.relatoriotecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Válvula do Relatório",
                "verbose_name_plural": "Válvulas dos Relatórios",
                "ordering": ["item"],
            },
        ),
    ]
