# Generated by Django 5.2.17 on 2026-09-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valvula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificação interna no Valvulman. Única por cliente.",
                        max_length=50,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("numero_serie", models.CharField(blank=True, max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(blank=True, max_length=150)),
                (
                    "diametro_nominal",
                    models.CharField(
                        blank=True,
                        help_text='Diâmetro como informado pelo cliente (ex.: 1", DN 25).',
                        max_length=50,
                    ),
                ),
                (
                    "pressao_ajuste",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "unidade_pressao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("psi", "psi"),
                            ("bar", "bar"),
                            ("kgf/cm²", "kgf/cm²"),
                        ],
                        default="psi",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valvulas",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Válvula",
                "verbose_name_plural": "Válvulas",
                "ordering": ["cliente__nome", "codigo"],
            },
        ),
        migrations.AddField(
            model_name="valvularelatorio",
            name="valvula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_relatorio",
                to="servicos.valvula",
            ),
        ),
        migrations.AddIndex(
            model_name="valvula",
            index=models.Index(fields=["tag"], name="servicos_va_tag_217847_idx"),
        ),
        migrations.AddIndex(
            model_name="valvula",
            index=models.Index(
                fields=["numero_serie"], name="servicos_va_numero__087cc7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="valvula",
            constraint=models.UniqueConstraint(
                fields=("cliente", "codigo"), name="uniq_valvula_cliente_codigo"
            ),
        ),
    ]
