# Generated by Django 5.2.17 on 2026-09-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0002_valvula_valvularelatorio_valvula_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificação interna no Valvulman. Única por cliente.",
                        max_length=50,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("numero_serie", models.CharField(blank=True, max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("manometro", "Manômetro")],
                        default="manometro",
                        max_length=20,
                    ),
                ),
                ("fabricante", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(blank=True, max_length=150)),
                (
                    "faixa_minima",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "faixa_maxima",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("psi", "psi"),
                            ("bar", "bar"),
                            ("kgf/cm²", "kgf/cm²"),
                        ],
                        default="psi",
                        max_length=10,
                    ),
                ),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Menor divisão da escala, na mesma unidade da faixa.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrumentos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
                "ordering": ["cliente__nome", "codigo"],
                "indexes": [
                    models.Index(fields=["tag"], name="servicos_in_tag_57a179_idx"),
                    models.Index(
                        fields=["numero_serie"], name="servicos_in_numero__d20061_idx"
                    ),
                    models.Index(fields=["tipo"], name="servicos_in_tipo_802113_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cliente", "codigo"),
                        name="uniq_instrumento_cliente_codigo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("faixa_minima__isnull", True),
                            ("faixa_maxima__isnull", True),
                            ("faixa_minima__lte", models.F("faixa_maxima")),
                            _connector="OR",
                        ),
                        name="instrumento_faixa_min_lte_max",
                    ),
                ],
            },
        ),
    ]
