# Generated by Django 5.2.17 on 2026-09-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0003_instrumento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Identificação persistente da calibração, única por instrumento.",
                        max_length=50,
                    ),
                ),
                ("data_calibracao", models.DateField()),
                ("procedimento", models.CharField(blank=True, max_length=150)),
                ("padrao_utilizado", models.CharField(blank=True, max_length=255)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibracoes",
                        to="servicos.instrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibração",
                "verbose_name_plural": "Calibrações",
                "ordering": ["-data_calibracao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="PontoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "valor_referencia",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "indicacao_instrumento",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("erro", models.DecimalField(decimal_places=3, max_digits=12)),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                (
                    "calibracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos",
                        to="servicos.calibracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto de calibração",
                "verbose_name_plural": "Pontos de calibração",
                "ordering": ["ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="calibracao",
            index=models.Index(fields=["numero"], name="servicos_ca_numero_00e6cb_idx"),
        ),
        migrations.AddIndex(
            model_name="calibracao",
            index=models.Index(
                fields=["data_calibracao"], name="servicos_ca_data_ca_8d9255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calibracao",
            index=models.Index(fields=["status"], name="servicos_ca_status_c203dc_idx"),
        ),
        migrations.AddIndex(
            model_name="calibracao",
            index=models.Index(
                fields=["resultado"], name="servicos_ca_resulta_271a42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calibracao",
            constraint=models.UniqueConstraint(
                fields=("instrumento", "numero"),
                name="uniq_calibracao_instrumento_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="pontocalibracao",
            constraint=models.UniqueConstraint(
                fields=("calibracao", "ordem"), name="uniq_ponto_calibracao_ordem"
            ),
        ),
        migrations.AddConstraint(
            model_name="pontocalibracao",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordem__gte", 1)),
                name="ponto_calibracao_ordem_positiva",
            ),
        ),
    ]
