# Generated by Django 5.2.17 on 2026-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0004_calibracao_pontocalibracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="criterio_aceitacao",
            field=models.CharField(
                blank=True,
                help_text="Origem do critério informado para esta calibração. Não implica norma automática.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="calibracao",
            name="tolerancia",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Tolerância absoluta na unidade do instrumento. Zero exige erro nulo.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="calibracao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tolerancia__isnull", True),
                    ("tolerancia__gte", 0),
                    _connector="OR",
                ),
                name="calibracao_tolerancia_nao_negativa",
            ),
        ),
    ]
