# Generated by Django 5.2.17 on 2026-09-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0005_calibracao_criterio_aceitacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("emitido_em", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("emitido", "Emitido"), ("cancelado", "Cancelado")],
                        default="emitido",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "calibracao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificado",
                        to="servicos.calibracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de calibração",
                "verbose_name_plural": "Certificados de calibração",
                "ordering": ["-emitido_em", "-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["numero"], name="servicos_ce_numero_919181_idx"
                    ),
                    models.Index(
                        fields=["status"], name="servicos_ce_status_642276_idx"
                    ),
                ],
            },
        ),
    ]
