# Generated by Django 5.2.17 on 2026-09-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0008_certificado_token_validacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="data_validade",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibracao",
            name="intervalo_validade_meses",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Prazo documental em meses, se informado. Não implica norma automática.",
                null=True,
            ),
        ),
    ]
