# Generated by Django 5.2.17 on 2026-09-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0009_calibracao_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="padrao_utilizado",
            field=models.TextField(
                blank=True,
                help_text="Snapshot documental do padrão utilizado nesta calibração.",
            ),
        ),
        migrations.CreateModel(
            name="PadraoMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificação interna do padrão no laboratório. Única.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("identificacao", models.CharField(max_length=255)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=150)),
                ("modelo", models.CharField(blank=True, max_length=150)),
                ("numero_serie", models.CharField(blank=True, max_length=100)),
                (
                    "faixa_minima",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "faixa_maxima",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("psi", "psi"),
                            ("bar", "bar"),
                            ("kgf/cm²", "kgf/cm²"),
                        ],
                        default="psi",
                        max_length=10,
                    ),
                ),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Menor divisão da escala, na mesma unidade da faixa.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        blank=True,
                        help_text="Número do certificado de calibração do próprio padrão.",
                        max_length=100,
                    ),
                ),
                (
                    "data_calibracao",
                    models.DateField(
                        blank=True,
                        help_text="Data em que o padrão foi calibrado.",
                        null=True,
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True,
                        help_text="Validade documental do certificado do padrão. Sem data, o uso não afirma prazo.",
                        null=True,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Padrão de medição",
                "verbose_name_plural": "Padrões de medição",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["numero_serie"], name="servicos_pa_numero__5cf29f_idx"
                    ),
                    models.Index(
                        fields=["fabricante"], name="servicos_pa_fabrica_562f9e_idx"
                    ),
                    models.Index(fields=["ativo"], name="servicos_pa_ativo_f8c24a_idx"),
                    models.Index(
                        fields=["data_validade"], name="servicos_pa_data_va_ec0c57_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("faixa_minima__isnull", True),
                            ("faixa_maxima__isnull", True),
                            ("faixa_minima__lte", models.F("faixa_maxima")),
                            _connector="OR",
                        ),
                        name="padrao_medicao_faixa_min_lte_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resolucao__isnull", True),
                            ("resolucao__gte", 0),
                            _connector="OR",
                        ),
                        name="padrao_medicao_resolucao_nao_negativa",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="calibracao",
            name="padrao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calibracoes",
                to="servicos.padraomedicao",
            ),
        ),
    ]
