# Generated by Django 5.2.17 on 2026-09-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0010_padrao_medicao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemOrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servico_solicitado",
                    models.CharField(
                        choices=[
                            ("calibracao", "Calibração"),
                            ("ajuste", "Ajuste"),
                            ("inspecao", "Inspeção"),
                            ("manutencao", "Manutenção"),
                            ("outro", "Outro"),
                        ],
                        default="calibracao",
                        max_length=20,
                    ),
                ),
                ("condicao_recebimento", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_execucao", "Em execução"),
                            ("aguardando_revisao", "Aguardando revisão"),
                            ("concluido", "Concluído"),
                            ("devolvido", "Devolvido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="recebido",
                        max_length=30,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_ordem_servico",
                        to="servicos.instrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da ordem de serviço",
                "verbose_name_plural": "Itens da ordem de serviço",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="calibracao",
            name="item_ordem_servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calibracoes",
                to="servicos.itemordemservico",
            ),
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=50, unique=True)),
                ("data_entrada", models.DateField()),
                ("data_previsao_entrega", models.DateField(blank=True, null=True)),
                ("data_entrega", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_execucao", "Em execução"),
                            ("aguardando_revisao", "Aguardando revisão"),
                            ("concluida", "Concluída"),
                            ("entregue", "Entregue"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=30,
                    ),
                ),
                ("solicitante", models.CharField(blank=True, max_length=150)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de serviço",
                "verbose_name_plural": "Ordens de serviço",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="itemordemservico",
            name="ordem_servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens",
                to="servicos.ordemservico",
            ),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=models.Index(fields=["numero"], name="servicos_or_numero_eeb1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=models.Index(fields=["status"], name="servicos_or_status_64ea73_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=models.Index(
                fields=["data_entrada"], name="servicos_or_data_en_d75e27_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemordemservico",
            constraint=models.UniqueConstraint(
                fields=("ordem_servico", "instrumento"), name="uniq_item_os_instrumento"
            ),
        ),
    ]
