# Generated by Django 5.2.17 on 2026-09-09 23:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0011_ordem_servico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=50, unique=True)),
                ("data_emissao", models.DateField()),
                ("data_validade", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviado", "Enviado"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("expirado", "Expirado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("condicoes_comerciais", models.TextField(blank=True)),
                ("cliente_nome_snapshot", models.CharField(blank=True, max_length=150)),
                (
                    "cliente_documento_snapshot",
                    models.CharField(blank=True, max_length=18),
                ),
                (
                    "cliente_endereco_snapshot",
                    models.CharField(blank=True, max_length=255),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamentos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-data_emissao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("calibracao", "Calibração"),
                            ("ajuste", "Ajuste"),
                            ("inspecao", "Inspeção"),
                            ("manutencao", "Manutenção"),
                            ("outro", "Outro"),
                        ],
                        default="calibracao",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ordem", models.PositiveIntegerField(default=1)),
                (
                    "instrumento_codigo_snapshot",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "instrumento_tag_snapshot",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "instrumento_serie_snapshot",
                    models.CharField(blank=True, max_length=100),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "instrumento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_orcamento",
                        to="servicos.instrumento",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="servicos.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do orçamento",
                "verbose_name_plural": "Itens do orçamento",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="orcamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_servico",
                to="servicos.orcamento",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.UniqueConstraint(
                condition=models.Q(("orcamento__isnull", False)),
                fields=("orcamento",),
                name="uniq_ordem_servico_orcamento",
            ),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["numero"], name="servicos_or_numero_4b98d9_idx"),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["status"], name="servicos_or_status_91a269_idx"),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(
                fields=["data_emissao"], name="servicos_or_data_em_1a984f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemorcamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gte", 1)),
                name="item_orcamento_quantidade_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemorcamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_unitario__gte", 0)),
                name="item_orcamento_valor_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemorcamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("desconto__gte", 0)),
                name="item_orcamento_desconto_nao_negativo",
            ),
        ),
    ]
