# Generated by Django 5.2.17 on 2026-09-10 00:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0012_orcamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=50, unique=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "acrescimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("valor_final", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("parcial", "Parcial"),
                            ("pago", "Pago"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("boleto", "Boleto"),
                            ("pix", "PIX"),
                            ("dinheiro", "Dinheiro"),
                            ("transferencia", "Transferência"),
                            ("cartao", "Cartão"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas",
                        to="servicos.orcamento",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas",
                        to="servicos.ordemservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança",
                "verbose_name_plural": "Cobranças",
                "ordering": ["-data_emissao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pagamento", models.DateField()),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("boleto", "Boleto"),
                            ("pix", "PIX"),
                            ("dinheiro", "Dinheiro"),
                            ("transferencia", "Transferência"),
                            ("cartao", "Cartão"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="servicos.cobranca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["data_pagamento", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(fields=["numero"], name="servicos_co_numero_c5d846_idx"),
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(fields=["status"], name="servicos_co_status_cafcc4_idx"),
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(
                fields=["data_vencimento"], name="servicos_co_data_ve_36b564_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cobranca",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_original__gte", 0)),
                name="cobranca_valor_original_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cobranca",
            constraint=models.CheckConstraint(
                condition=models.Q(("desconto__gte", 0)),
                name="cobranca_desconto_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cobranca",
            constraint=models.CheckConstraint(
                condition=models.Q(("acrescimo__gte", 0)),
                name="cobranca_acrescimo_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cobranca",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ordem_servico__isnull", False)),
                fields=("ordem_servico",),
                name="uniq_cobranca_ordem_servico",
            ),
        ),
    ]
