# Generated by Django 5.2.17 on 2026-09-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0013_cobranca_pagamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibracao",
            options={
                "ordering": ["-data_calibracao", "-criado_em"],
                "permissions": [
                    ("concluir_calibracao", "Pode concluir calibração"),
                    ("revisar_calibracao", "Pode revisar calibração"),
                    ("reabrir_calibracao", "Pode reabrir calibração"),
                ],
                "verbose_name": "Calibração",
                "verbose_name_plural": "Calibrações",
            },
        ),
        migrations.AlterModelOptions(
            name="certificadocalibracao",
            options={
                "ordering": ["-emitido_em", "-criado_em"],
                "permissions": [
                    ("emitir_certificado", "Pode emitir certificado de calibração"),
                    ("cancelar_certificado", "Pode cancelar certificado de calibração"),
                ],
                "verbose_name": "Certificado de calibração",
                "verbose_name_plural": "Certificados de calibração",
            },
        ),
        migrations.AlterModelOptions(
            name="cobranca",
            options={
                "ordering": ["-data_emissao", "-criado_em"],
                "permissions": [
                    ("cancelar_cobranca", "Pode cancelar cobrança"),
                    ("registrar_pagamento", "Pode registrar pagamento"),
                ],
                "verbose_name": "Cobrança",
                "verbose_name_plural": "Cobranças",
            },
        ),
        migrations.AlterModelOptions(
            name="orcamento",
            options={
                "ordering": ["-data_emissao", "-criado_em"],
                "permissions": [
                    ("enviar_orcamento", "Pode enviar orçamento"),
                    ("aprovar_orcamento", "Pode aprovar orçamento"),
                    ("recusar_orcamento", "Pode recusar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                    (
                        "gerar_ordem_servico",
                        "Pode gerar ordem de serviço a partir do orçamento",
                    ),
                ],
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="ordemservico",
            options={
                "ordering": ["-criado_em"],
                "permissions": [
                    ("iniciar_ordem", "Pode iniciar ordem de serviço"),
                    ("revisar_ordem", "Pode enviar ordem de serviço para revisão"),
                    ("concluir_ordem", "Pode concluir ordem de serviço"),
                    ("entregar_ordem", "Pode entregar ordem de serviço"),
                    ("cancelar_ordem", "Pode cancelar ordem de serviço"),
                ],
                "verbose_name": "Ordem de serviço",
                "verbose_name_plural": "Ordens de serviço",
            },
        ),
    ]
