# Generated by Django 5.2.17 on 2026-09-13 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0016_orcamento_misto_e_contato_os"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecucaoValvula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("executor_nome", models.CharField(blank=True, max_length=150)),
                ("executado_em", models.DateTimeField(blank=True, null=True)),
                ("revisor_nome", models.CharField(blank=True, max_length=150)),
                ("revisado_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes_revisao", models.TextField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao_servico", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("valvula_codigo", models.CharField(blank=True, max_length=50)),
                ("valvula_tag", models.CharField(blank=True, max_length=100)),
                ("valvula_numero_serie", models.CharField(blank=True, max_length=100)),
                ("valvula_fabricante", models.CharField(blank=True, max_length=150)),
                ("valvula_modelo", models.CharField(blank=True, max_length=150)),
                (
                    "valvula_diametro_nominal",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "valvula_pressao_ajuste",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "valvula_unidade_pressao",
                    models.CharField(blank=True, max_length=10),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes_valvula_executadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_ordem_servico",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execucao_valvula",
                        to="servicos.itemordemservico",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes_valvula_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Execução de válvula",
                "verbose_name_plural": "Execuções de válvula",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="servicos_ex_status_8c5b0e_idx"
                    ),
                    models.Index(
                        fields=["resultado"], name="servicos_ex_resulta_e37949_idx"
                    ),
                    models.Index(
                        fields=["data_inicio"], name="servicos_ex_data_in_8daf05_idx"
                    ),
                ],
            },
        ),
    ]
