# Generated by Django 5.2.17 on 2026-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("cep", models.CharField(max_length=9)),
                ("endereco", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
